### ISSUE TITLE
La puerta debería mantenerse abierta si hay un jugador en el área

### ISSUE THREAD

**Issue by Braisa** [codemonsters/racekombat#25]
También debería hacerlo si al menos un jugador ya ha cruzado el límite.
Además, no debería cerrarse si un jugador está debajo de ella. Quizás para solucionarlo se puede extender el área para que incluya el hueco de la puerta.

**Comment by yagueto** [comment]
Arreglado lo de que te aplaste la puerta :dizzy_face:  

> También debería hacerlo si al menos un jugador ya ha cruzado el límite.

¿Debería? Entonces las personas podrían volver atrás; no se si debería ser así. De todas formas, se había hablado que el juego no empezara hasta que un número mínimo de jugadores (¿podría eso arreglarlo?)
