### ISSUE TITLE
Saltos infinitos

### ISSUE THREAD

**Issue by Braisa** [codemonsters/racekombat#33]
A veces el jugador es capaz de saltar infinitamente. No pierde la capacidad al tocar el suelo, ni muriendo ni al finalizar la carrera. Puede ocurrirle a un único jugador mientras que el resto funcionan como esperado. Además, los saltos infinitos no activan la animación de salto.

El problema parece estar relacionado con la muerte. Para replicarlo, en mi caso funciona con tener dos jugadores en pantalla al mismo tiempo y matar en un agujero a uno o a ambos. Cuando reviven, uno de los jugadores es capaz de saltar de forma ilimitada.

**Comment by yagueto** [comment]
cc @Autotren

**Comment by Autotren** [comment]
Arreglado por ahora 341c5c64bc67d842d7711b365c8e4715d0b3c24a
