### ISSUE TITLE
Añadir botón para regresar a la pantalla de inicio/pausa

### ISSUE THREAD

**Issue by yagueto** [codemonsters/racekombat#40]
¿Sería útil añadir tanto un botón de pausa como un botón para volver a la pantalla de inicio? El segundo tendría especial sentido para poder cambiar de mapa. Otra opción (quizás mejor) sería permitir votar cada vez que comience, pero podría ser más difícil de implementar...

**Comment by yagueto** [comment]
También podría ser una puerta por la que tenga que salir la mitad de la gente...

**Comment by asexto** [comment]
ヽ(´▽`)/
