### ISSUE TITLE
La cámara en ocasiones está demasiado alta

### ISSUE THREAD

**Issue by asexto** [codemonsters/racekombat#42]
Cuando aparecen plataformas flotantes muy altas, la media de alturas del suelo es también alta y eso hace que en ocasiones el suelo no se vea. Una solución podría ser poner una altura máxima respecto a la media del suelo (sin tener en cuenta las plataformas). Otra opción podría ser ignorar las plataformas flotantes a la hora de calcular la media de altura de la cámara.

**Comment by yagueto** [comment]
Aparentemente solucionado, aunque en teoría podrían reaparecer problemas en menús manuales
