### ISSUE TITLE
En Windows es necesario ejecutar el juego (servidor) como administrador para que al app del gamepad se pueda conectar

### ISSUE THREAD

**Issue by asexto** [codemonsters/racekombat#46]
Si realmente es necesario, deberíamos mostrar este requisito claramente al usuario

**Comment by yagueto** [comment]
Por lo visto, problemas con el firewall de Windows. Otra solución menos destructiva que darle permisos a tope es reconfigurar el firewall y permitir los puertos 31416 y/o 4242 (puede que algún otro también, pero creo que con sólo esos fucnionará)
