### ISSUE TITLE
Crear en Godot un tilemap de prueba 

### ISSUE THREAD

**Issue by codemonsters** [codemonsters/racekombat#5]

**Comment by asexto** [comment]
A modo de prueba usaremos este tileset: https://opengameart.org/content/a-platformer-in-the-forest

**Comment by asexto** [comment]
Este tutorial está siendo útil: https://www.davidepesce.com/2019/10/18/godot-tutorial-7-using-tile-maps-to-create-game-map/

**Comment by Ypablosv5Y** [comment]
Video generar tilemap https://www.youtube.com/watch?v=X0PZDv-urEw

**Comment by Ypablosv5Y** [comment]
Explicando := https://es.stackoverflow.com/questions/386750/qu%C3%A9-significa-en-python
